apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - db-credentials-secret.yaml
  - ghcr_secret.yaml
  - deployment.yaml
  - service.yaml
  - istio_gateway.yaml
  - istio_virtualservice.yaml